### ISSUE TITLE
Upgrade fop to 2.0

### ISSUE THREAD

**Issue by ProgramFan** [asciidoctor/asciidoctor-fopub#47]
Apache has released FOP 2.0 in June 2015. It supports OpenType CCF fonts. I wonder if we can upgrade FOP to 2.0 and did a few experiments and failed.

1. Change FOP version in `build.gradle` to 2.0 and reinitialize.

The compilation of `main/org/xxxx/InputHandler.java` failed due to invalid interface called.

2. I found an InputHandler.java in FOP 2.0 source and replaced `src/main/XXX/InputHandler.java`.

The compilation succeeded and initialization OK. But fopub crashes with a lot of java errors when running `./fopub XXX.xml`. 

I don't know java so I can not go deeper. But can it be solved? I don't quite understand why there are FOP's source code in fopub.

**Comment by mojavelinux** [comment]
>  I don't quite understand why there are FOP's source code in fopub.

The InputHandler class is there to work around a bug where fop is reaching out to the internet because it does not (or did not) properly register the resolver.

Here's my patch against the Apache FOP source code.

https://github.com/mojavelinux/apache-fop/commit/8ab195000e723c90c8fec70adad4175f1674a844

We should probably document this in the README to make it more clear.

I see the bug is still not fixed in Apache FOP 2.0, so we'd still need the patch.

**Comment by mojavelinux** [comment]
I'm looking for a new maintainer for Asciidoctor fopub as my focus has shifted to Asciidoctor PDF. I'm in favor of the migration to FOP 2.0 as we certainly want to stay current. However, testing will be needed to ensure we don't break existing uses.

**Comment by ProgramFan** [comment]
@mojavelinux I tried apply your patch to the latest InputHandler.java and fopub initializes sucessfully. But fopub still crashes. It can reproduced by running fopub in the README.adoc of this repo.

```
org.apache.fop.apps.FOPException: java.lang.NullPointerException
javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:289)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2416)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1374)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemIf.execute(ElemIf.java:160)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2281)
	at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1367)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:709)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1284)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1262)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:286)
	... 3 more
Caused by: java.lang.NullPointerException
	at org.apache.fop.layoutmgr.list.ListItemLayoutManager.getCombinedKnuthElementsForListItem(ListItemLayoutManager.java:405)
	at org.apache.fop.layoutmgr.list.ListItemLayoutManager.getNextKnuthElements(ListItemLayoutManager.java:326)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:239)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextChildElements(BlockStackingLayoutManager.java:498)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.list.ListBlockLayoutManager.getNextKnuthElements(ListBlockLayoutManager.java:103)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:239)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextChildElements(FlowLayoutManager.java:223)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addChildElements(FlowLayoutManager.java:147)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:116)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:69)
	at org.apache.fop.layoutmgr.PageBreaker.getNextKnuthElements(PageBreaker.java:252)
	at org.apache.fop.layoutmgr.AbstractBreaker.getNextBlockList(AbstractBreaker.java:643)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:178)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:158)
	at org.apache.fop.layoutmgr.AbstractBreaker.doLayout(AbstractBreaker.java:384)
	at org.apache.fop.layoutmgr.PageBreaker.doLayout(PageBreaker.java:112)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:138)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:130)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:360)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xml.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:261)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1399)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	... 23 more

---------

; SystemID: file:////home/zyang/.local/asciidoctor-fopub/build/fopub/docbook/fo/docbook.xsl; Line#: 310; Column#: 54
javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2416)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1374)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemIf.execute(ElemIf.java:160)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2281)
	at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1367)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:709)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1284)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1262)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:286)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
Caused by: java.lang.NullPointerException
	at org.apache.fop.layoutmgr.list.ListItemLayoutManager.getCombinedKnuthElementsForListItem(ListItemLayoutManager.java:405)
	at org.apache.fop.layoutmgr.list.ListItemLayoutManager.getNextKnuthElements(ListItemLayoutManager.java:326)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:239)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextChildElements(BlockStackingLayoutManager.java:498)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.list.ListBlockLayoutManager.getNextKnuthElements(ListBlockLayoutManager.java:103)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:239)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextChildElements(FlowLayoutManager.java:223)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addChildElements(FlowLayoutManager.java:147)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:116)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:69)
	at org.apache.fop.layoutmgr.PageBreaker.getNextKnuthElements(PageBreaker.java:252)
	at org.apache.fop.layoutmgr.AbstractBreaker.getNextBlockList(AbstractBreaker.java:643)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:178)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:158)
	at org.apache.fop.layoutmgr.AbstractBreaker.doLayout(AbstractBreaker.java:384)
	at org.apache.fop.layoutmgr.PageBreaker.doLayout(PageBreaker.java:112)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:138)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:130)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:360)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xml.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:261)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1399)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	... 23 more
---------
java.lang.NullPointerException
	at org.apache.fop.layoutmgr.list.ListItemLayoutManager.getCombinedKnuthElementsForListItem(ListItemLayoutManager.java:405)
	at org.apache.fop.layoutmgr.list.ListItemLayoutManager.getNextKnuthElements(ListItemLayoutManager.java:326)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:239)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextChildElements(BlockStackingLayoutManager.java:498)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.list.ListBlockLayoutManager.getNextKnuthElements(ListBlockLayoutManager.java:103)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:239)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextChildElements(FlowLayoutManager.java:223)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addChildElements(FlowLayoutManager.java:147)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:116)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:69)
	at org.apache.fop.layoutmgr.PageBreaker.getNextKnuthElements(PageBreaker.java:252)
	at org.apache.fop.layoutmgr.AbstractBreaker.getNextBlockList(AbstractBreaker.java:643)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:178)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:158)
	at org.apache.fop.layoutmgr.AbstractBreaker.doLayout(AbstractBreaker.java:384)
	at org.apache.fop.layoutmgr.PageBreaker.doLayout(PageBreaker.java:112)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:138)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:130)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:360)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xml.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:261)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1399)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1374)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemIf.execute(ElemIf.java:160)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2281)
	at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1367)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:709)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1284)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1262)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:286)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
```

Asciidoctor-PDF is promissing and evolves quickly. Thanks you for the nice job. I don't program in Java so I have no idea on how to fix the problem.

**Comment by mojavelinux** [comment]
It's very possible that the DocBook 1.78.1 templates are not compatible with Apache FOP 2. If that's the case, then this is not an issue with fopub, but rather with DocBook itself (which fopub wraps). I'd look for news about DocBook support for Apache FOP 2. Once we get that confirmation, then it can be integrated into fopub.

**Comment by mojavelinux** [comment]
Sure enough, I found a thread on the DocBook Apps mailinglist that confirms there is an incompatibility.

https://lists.oasis-open.org/archives/docbook-apps/201506/msg00020.html

Until that is resolved, there's little we can do in fopub (because fopub is just a wrapper).

**Comment by ProgramFan** [comment]
@mojavelinux Thanks for the information, I think we will just wait. :)

**Comment by rahmanusta** [comment]
@ProgramFan @mojavelinux I tried to switch fop 1.1 to 2.0 in my project and I'm getting same exception. We need to wait Docbook's update :)

**Comment by rahmanusta** [comment]
@mojavelinux @ProgramFan 

I investigated that by using the default docbook.xsl, fop 2.0 generates PDF normally;

But with fo-pdf.xsl in fopub, it throws NullPointerException when generating PDF.

After several tries I understand that problem causes from `monospace.properties`, `verbatim.properties`  and  `shade.verbatim.style` attributes and it's bottom (padding/margin) attributes.

For example; If you use below Asciidoc note;

```asciidoc
[NOTE]
====
Merhaba Dünya

[source,java]
----
//
----
====
```

PDF generation will be failed.

But if you change the followings, PDF generation will be OK.

https://github.com/asciidoctor/asciidoctor-fopub/blob/master/src/dist/docbook-xsl/fo-pdf.xsl#L143

Make zero bottom padding .3em .25em 0 .25em 

https://github.com/asciidoctor/asciidoctor-fopub/blob/master/src/dist/docbook-xsl/fo-pdf.xsl#L149

Remove line 153

https://github.com/asciidoctor/asciidoctor-fopub/blob/master/src/dist/docbook-xsl/fo-pdf.xsl#L237

Make zero bottom padding 1em .5em 0 .5em

What do you think?

**Comment by mojavelinux** [comment]
Thanks for looking into this @rahmanusta. Please proceed. In fact, given that this project is critical to AsciidocFX at the moment, what do you think if I added you as an administrator on it so that you can ensure that you have the control to make fixes when you need to make them?

**Comment by rahmanusta** [comment]
@mojavelinux Of course, fopub project is base for AsciidocFX's PDFConverter and it has critical position. We can contribute to fopub project for that and any other fixes and improvements.

**Comment by ProgramFan** [comment]
Nice work

**Comment by mojavelinux** [comment]
We're now on fop 2.1 thanks to @rahmanusta. If you notice any problems, please report them.

**Comment by mojavelinux** [comment]
Make sure you run a clean build to get the latest dependencies.

```
./gradlew clean
```

**Comment by rahmanusta** [comment]
Thank you @mojavelinux.
